/**
 * All right is from Author of the file,to be explained in comming days.
 * Jan 2, 2013
 */
package com.graphscape.gwt.commons.provider.default_.handler.message;

import com.graphscape.gwt.commons.mvc.ControlManagerI;
import com.graphscape.gwt.commons.mvc.support.UiHandlerSupport;
import com.graphscape.gwt.commons.provider.default_.frwk.login.AccountsLDW;
import com.graphscape.gwt.commons.provider.default_.frwk.login.AnonymousAccountLDW;
import com.graphscape.gwt.commons.provider.default_.handler.action.AutoLoginHandler;
import com.graphscape.gwt.core.ContainerI;
import com.graphscape.gwt.core.ClientI;
import com.graphscape.gwt.core.data.message.MessageData;
import com.graphscape.gwt.core.event.EndpointMessageEvent;
import com.graphscape.gwt.core.message.MessageHandlerI;

/**
 * @author wu
 * 
 */
public class SignupAnonymousSuccessMH extends UiHandlerSupport implements
		MessageHandlerI<EndpointMessageEvent> {

	/*
	 * Jan 2, 2013
	 */
	/**
	 * @param c
	 */
	public SignupAnonymousSuccessMH(ContainerI c) {
		super(c);
	}

	@Override
	public void handle(EndpointMessageEvent t) {
		//
		ClientI client = t.getSource().getClient(true);
		ControlManagerI cm = client.getChild(ControlManagerI.class, true);
		MessageData res = t.getMessage();//

		AccountsLDW sai = AccountsLDW.getInstance();
		// save to client and schedule to send again the auth action,see
		// processRequest of this.
		String accId = (String) res.getPayload("accountId", true);//
		String password = (String) res.getPayload("password", true);
		// accountId and password generated by serverside,so saving it
		// before auth is ok.
		AnonymousAccountLDW aal = sai.getAnonymous();
		aal.save(accId, password);// save anonymous
									// account.

		AutoLoginHandler.autoLogin(this.getEndpoint(), t.getSource());

	}

}
