#include "../DefineMql.h"
#include "system/TaSystem.cpp"
#include "system/TaLang.cpp"
#include "system/TaObject.cpp"
#include "system/TaException.cpp"
#include "common/lang/TaDateTime.cpp"
#include "common/lang/TaString.cpp"
#include "common/lang/TaColor.cpp"

#include "system/TaRef.cpp"
#include "system/TaRefArray.cpp"
#include "common/ref/TaRefList.cpp"
#include "common/ref/TaStringRefMap.cpp"
#include "common/ref/TaRefStack.cpp"
#include "common/config/TaConfig.cpp"
#include "common/config/TaConfigFactory.cpp"
#include "common/config/TaJsonConfigFactory.cpp"

#include "common/json/TaJsonValue.cpp"
#include "common/json/TaJsonString.cpp"
#include "common/json/TaJsonArray.cpp"
#include "common/json/TaJsonObject.cpp"
#include "common/json/TaJsonParser.cpp"

#include "common/lang/TaDouble.cpp"
#include "common/lang/TaInteger.cpp"
#include "common/web/TaWebHeaders.cpp"
#include "common/web/TaWebRequest.cpp"
#include "common/web/TaWebResponse.cpp"
#include "common/web/TaWebClient.cpp"
#include "mql/TaMql.cpp"
#include "mql/TaMqlInfos.cpp"

#include "common/TaStringBuffer.cpp"
#include "common/log/TaLogger.cpp"
#include "common/log/TaLoggerConfiguration.cpp"
#include "common/log/TaLoggerFactory.cpp"
#include "common/TaConstants.cpp"
#include "common/lang/TaVDir.cpp"
#include "common/TaNotifier.cpp"

#include "core/container/TaContainer.cpp"
#include "core/container/TaContainerAwareObject.cpp"

#include "core/advisor/TaOrderAdvisor.cpp"
#include "core/advisor/TaTakeProfitCalculator.cpp"
#include "core/advisor/opener/TaOrderOpeningAction.cpp"
#include "core/advisor/opener/TaOrderOpenner.cpp"
#include "core/advisor/profit/TaDayAtrBasedTakeProfitCalculator.cpp"
#include "core/advisor/support/TaBaseOrderAdvisor.cpp"
#include "core/advisor/support/TaBaseOrderOpenner.cpp"
#include "core/advisor/support/TaNewBarOrderAdvisor.cpp"
#include "core/advisor/support/TaBaseOrderUpdator.cpp"

#include "core/advisor/updator/TaOrderUpdator.cpp"
#include "core/advisor/updator/TaOrderUpdatingAction.cpp"
#include "core/advisor/updator/TaStage2OrderUpdator.cpp"
#include "core/advisor/updator/TaStagesOrderUpdator.cpp"

#include "core/driver/TaDriver.cpp"

#include "core/order/TaOrderSender.cpp"
#include "core/order/TaOrderExplainer.cpp"
#include "core/order/TaOrderComments.cpp"
#include "core/order/TaStagesOrderExplainer.cpp"

#include "core/tick/TaTickHandler.cpp"
#include "core/tick/support/TaOrderAdvisorTickHandler.cpp"
#include "core/timebar/TaTimeBar.cpp"
#include "core/timebar/TaTwoMovingAverageTimeBar.cpp"
#include "core/timebar/TaMovingAverageTimeBar.cpp"

#include "core/risk/TaRiskControl.cpp"
#include "core/risk/TaTotalLossWeeklyRiskControl.cpp"
#include "core/tick/support/TaCollectionTickHandler.cpp"

#include "trader/td0001/TaTd0001Driver.cpp"
#include "trader/td0001/TaMa2OrderAdvisor.cpp"
#include "trader/td0001/TaBootstrap.cpp"
#include "trader/td0001/TaTesterChart.cpp"
#include "trader/td0001/TaMa2OrderOpenner.cpp"
#include "trader/td0001/TaMa2OrderUpdator.cpp"
#include "trader/td0001/TaMa2OrderUpdator2.cpp"
#include "trader/td0001/TaMa2OrderExplainer.cpp"

#include "agent/TaAgent.cpp"



